// https://www.codewars.com/kata/5a145ab08ba9148dd6000094/train/javascript

function doubles(s){
  const arr = s.split('')
  arr.forEach((char, idx)=>{
    if (char === arr[idx+1]){
      arr[idx]=''
      arr[idx+1]=''
    }
  })
  if (s.length === arr.join('').length){
    return arr.join('')
  } else {
    return doubles(arr.join(''))
  }
}

console.log(doubles('zzzzykkkd'))
console.log(doubles('jbbzeemmkkdyyqqfvssiibftrmmaalaaooqqxbpeedbbfrrooiijoojhnoorssmmsswwggpmmnmmdggwwmmrviiqqkkssbptwwvnfoodhndiikkdaarqqzkkjtzluuuuqqdxpznfwwvaaqquuhxxggccyyvpoobkkoozmmggaayyldssoodvjuuuuttqqqqggqqwwpyyccfteebwwwwssteedfaatbrlfyybjkkjpccuubkkggyyoossxzqqfneevzjkkggyywwnrpfzfnwwteeyykkphccoolyyjplbiiruufyytggggsswwtiieevoohxpqqccjtiifccqqiifeewwuupzbccwwsstccssaaggxtloouusseehjdqqtzpoojdhaahdkkbyyiivrssdmmccggpccssvxiiyyqqyybbqqssssqqzhdblbwwwwiipmmpiifjrrhzrpiilbzwwhmmxggwwiiiixzuummxfootuutuuccookkliidlccreeziieebiirddmmssaabkkfwwaaxggaaaafkkhheeiisseemmviivzcczlhccxfrooyyiirvjqqtkkxfpggzggwwhmmfuuiiaaddnhtlfmmzwwtqqvfiithjaaqqvooeemmccpmmbjzssuunmmaaxnhiiuuzbaaqqaaqqssmmmmtoouuhzeemmruuaabqqbssccwwfccroobcckkfaaccxmmkkeebeehloooonkkooggaapjmmiiprssbqqrpxlaaxvyytxggiiuujcciixuujiizxoolnpoohyyooggeeffryytyyuurtprdqqzoovjbthnfwwaaaahtggdgglwwqqjggvuuoossmmuulaaxrsspbootlsskkggsswwrkksshnyyccdkkuutdyyuuyyhqqyyeewwaavuuhooaaaaqqlwwcceeggaakkzruuqqroouussrdpplkkzflxtbtkkjlpeeoodtdvpvoouudpjlllmmhnoowwljhvyyrookkrssiifooloossjlsscckkggkknhzqqqqmmeemmtvhkkuuooyyccaakkccaaaauuxaadjjggaajyyjpxfxpnggqqfwwuussjiiuummluussbbpkknpaassssssuuplcczkkbuuiidjggyyrqqiixiieeyyznpviimmnyyaayyvoohboojkkcclccyybwwyymmzeessvhvqqffmmbbbiiccnaatfvrfruuuutyynaafkkvzduuzkkkkkkljdwwtuutaadoorrtccaafmmaaztdfoobtiieeznggyyeetccggsshssheedbphjiidmmzeevxnlnxqqdjkkeeviizvffpqqjbllqqbtpmmhyyblooaadlmmldxlhlccaadoobssxyyggreefeeooooaaccvqqqqzvjroommuuaaooggwwvvfggggqqggxltaafeerpdfdiibjeeyyfmmuuftfmmnhiihxzeekkaazuuqqeevjbffncczuummkkbhtxaakkjwwggtggfxmmdqqqqfyywwzaammsstmmvjzqqggxkkxcciigglaanzeefwwftggaaccjaapmmyyqqaafooxssqqzmmggwwziixtwwrnnbzfqqwwiipljlooduudssptggyyccbhtrpaakkuummccdyybzoosseekkeeeeyymmiimmfeeuubrznmmphkkggdssaabeeggnnkkyysscchggkkuudhzdkkptnggdccwwjtleebpaaxndjoossjuukknpdhootdkkoonryynvtxrvqquukkkkpaariiqqtrjbcczrggpjaavooootpaammtyyrxggthuuggliiqqtrmmdrvjztoocceeooeeeexmmzssvoolyyggiizggggdvfwweeggwwjnwwpssrlzgglkkoommyygguuxhoolmmbrbkkggppccniiwwzzooqqhrjmmvpfffwwfvpssffccmmdoofwwnzjttjprssaahpdwwheegguublyyggeeyyxwwuufnboobjneessoodsspuuyyeebggssduuprxeeddftvhxmmccbkkeefxiissqqwwxmmccaajmmeetkkxxqqkkvkkuuzmmnvvccssccccaaqqssnggtwwwwmmooeemmbiikklmmiikkjccmmqqzeessqqiidlzdzwwyyzkknjiiwwyywwtkkrfrssnteehggjwwmmwwwwuuqqqqfpfmmyyuudrmmmmggyyccfeeeeaarnccggpnyyhpkkssqqlyyggpxdggggaazuuyywwzzrccsszlwwmmmmooggkklssdwwnssmmkkgglyyaadttrkkoozfbccznpqqaaaajhiibffmmbfxkkdeekkggaajaauuccaafuufzkkrqqbmmtxyyggeefiicckkcczrmmnhookkssmmxcczhiijcckkkktmmbxmmmmqqccwwyyccaaqqooaafaarccmmlzzmmlssuubxvfbkktfccxqqwwvhbhyyeejoozqqthggtccjuuqqggqqtmmkknjaataaggeeoopaaiifwwkkzrnuuggjhdiilaabuufxvlzyydwwjtiikkggkkggleehwwoommhxvbeedluuiirkksswwbmmsskkcctxwwkkccccduuzqqdsszssaatlpaaaatjxzuukkssjhbpndggssqqdnbfqqjssoohneedjxiiwwoommraajqqxpyyggmmxwwzrmmfprlvnbuufhlmmhbeeqqqqiiiilqqvyyssiisskkdssooiinnmmvqqaafvzxnyyeezggveenwwiiuuiiqqzfqqlkkkkmmfrjtdlyynfreeggtjfjeedtlrbrggaajyywwoodvyypwwtnqqssdaajlxsseesspoossxlxaacchnddxaaggmmzzrpooooiitiirbuurxiissiifqqccqqjyyccuudqqkkdmmkkaakkuuvlhyyccggrvkkvqqzeerdlggzkkiijiijwwrccfyytrggggbduubmmaavyyfaahzqqaasseehlphyypfqqmmeerveenkkccxyyfkkddnvkkpffxuuiiqqqqzzbdbbssduuwwaauuookkuulbluutyyteemmwwjkkjhdsseeaaaaaawwvcceeyyaaeeggdbeeyynjtnccveemmaadmmrssggiiiiuudyyhviiggnssfdyyvlzggfhrjyybzxvvvbdrkknbccggjleexkkzwwbduufyyooccpaauufiizlrttcciilmmggnggreewwkkuujcckksspfxnssjbqqiikkwwssyyyytaaccveeggmmpggtqqaammryyggii'))

// top answer

// for loop

function doubles(s) {
  const cs = [];
  for (const c of s) {
    if (cs.length != 0 && cs[cs.length - 1] == c)
      cs.pop();
    else
      cs.push(c);
  }
  return cs.join('');
}

// short answer
// regex
doubles=d=s=>(x=s.replace(/(\w)\1/g,""))==s?s:d(x);